[phases.setup]
nixPkgs = ["nodejs", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = [
  "chmod +x build.sh",
  "./build.sh"
]

[start]
cmd = "node dist/server/node-build.mjs"
